In [4]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [17]:
a = np.arange(5)[:, np.newaxis]

In [23]:
a = a.ravel()

In [32]:
a = np.zeros((3, 2))
b = a.T.reshape(3*2)


In [34]:
b

array([9., 0., 0., 0., 0., 0.])

In [36]:
a = np.arange(4*3*2).reshape(4, 3, 2)

In [38]:
a.shape

(4, 3, 2)

In [43]:
b = a.transpose()
b.shape

(2, 3, 4)

In [58]:
b = b.transpose(1, 0, 2)
b.shape

(2, 3, 4)

In [96]:
a = np.arange(3*4)
np.random.shuffle(a)
a = a.reshape((3, 4))
a

array([[ 8,  3,  7,  9],
       [ 4,  0, 10,  5],
       [11,  6,  1,  2]])

In [106]:
a1 = np.sort(a)
a.sort()

In [1]:
print (np.array_equal(a, a1))
print (a.all(a1))

NameError: name 'np' is not defined

In [100]:
np.random.randn(3, 4)

array([[-0.93154935, -0.58420476, -0.72293451, -0.28957983],
       [-0.63958579, -1.62829825,  1.48738014,  1.25758059],
       [-1.76037621,  0.28795569, -0.79069534, -1.96687249]])